### ISSUE TITLE
Adding 4 at random places

### ISSUE THREAD

**Issue by vkasharma** [Parveshdhull/AutoTyper#2]
![image](https://user-images.githubusercontent.com/11803704/117536884-413c2b80-b01b-11eb-842a-a8fc1a86f740.png)

**Comment by Parveshdhull** [comment]
The program works with Notepad RT, but Notepad RTX++ has some kind of protection that doesn't allow typing simulation and inserts random "4".  

**Solution:**
1. First close Notepad RTX++ and StartTXT completely, using task manager and also find background process and end it. Or just shutdown and restart your PC
2. Download old Notepad RT from [here](https://drive.google.com/file/d/1otYaeQkaDML3qXh8L4Nee3dXWSTytTF6/view?usp=sharing)
3. Now you can type in this software using my auto typer Exe
4. This software saves files as .xtt, just rename it to .rtx (From folder view enable extensions to change) 
5. Voila, now the project is done. You can send this file. If you want to try, you can also open this file in notepad rtx++ and it will open.

**PS**: Both Notepad RT and Notepad RTX++ writes same content, that's why changing extension will work. If you want to test on own. Write small word in both and open both in notepad, and you will see same base64 encoded data.

**Comment by varsharamanujam** [comment]
I am having the same issue as well.. I tried the above steps you have mentioned but it's still the same.

**Comment by Anupamaburugupalli** [comment]
I use WinRar and eventhough i change the format of it from .xtt to .nts the notes does not open and says this not human speed. how do i proceed ?
